//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrandOutlet.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandRole
    {
        public long Id { get; set; }
        public string Roles { get; set; }
    
        public virtual BrandRole BrandRoles1 { get; set; }
        public virtual BrandRole BrandRole1 { get; set; }
    }
}
