//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrandOutlet.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandOutletLog
    {
        public long Id { get; set; }
        public Nullable<System.Guid> OutletTokenId { get; set; }
        public Nullable<long> RetailerId { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<long> SubCategoryId { get; set; }
        public string SubCategoryName { get; set; }
        public Nullable<long> Quantity { get; set; }
        public string Type { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
