//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrandOutlet.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandMainMenu
    {
        public BrandMainMenu()
        {
            this.BrandSubMenus = new HashSet<BrandSubMenu>();
        }
    
        public long Id { get; set; }
        public string MainMenu { get; set; }
    
        public virtual ICollection<BrandSubMenu> BrandSubMenus { get; set; }
    }
}
