//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrandOutlet.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandSubMenu
    {
        public long Id { get; set; }
        public string SubMenu { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Nullable<long> MainMenuId { get; set; }
        public Nullable<long> RoleId { get; set; }
        public Nullable<bool> IsMenue { get; set; }
    
        public virtual BrandMainMenu BrandMainMenu { get; set; }
    }
}
