//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrandOutlet.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailer
    {
        public long Id { get; set; }
        public string District { get; set; }
        public string DistributorName { get; set; }
        public string DistributorCode { get; set; }
        public string RetailerName { get; set; }
        public string RetailerAddress { get; set; }
        public string OwnerName { get; set; }
        public string PhoneNumber { get; set; }
        public string MonthlyAverageSale { get; set; }
        public string MonthlyAverageSaleOfWalton { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime AddedDate { get; set; }
    }
}
