//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrandOutlet.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCreateAccount
    {
        public long Id { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ReTypePassword { get; set; }
        public string Email { get; set; }
        public Nullable<long> Mobile { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
